version: 2

updates:

  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "16:30"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - devops-admin
    reviewers:
      - devops-admin
    commit-message:
      prefix: "SFDC-1234: "
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "16:30"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - devops-admin
    reviewers:
      - devops-admin
    commit-message:
      prefix: "SFDC-1234: "
